version 1.0

## HTX metagenomic triage — WDL wrapper.
##
## One PFI HTML report per sample in, a tier per organism and per resistance gene out.
## No reference database, no aligner, no network: the container carries the rules and the
## engine is Python 3 standard library only, so a task is CPU-trivial and fully reproducible.
##
## Two entry points:
##   TriageBatch (this workflow) — the normal case. Cross-sample enrichment (gate 8) needs the
##                                 whole batch in one process, so all reports go to one task.
##   TriageOne   — a single report. Gate 8 goes inert and says so; use only when there is
##                 genuinely one sample, not to parallelise a batch.
##
## IMPORTANT — batch comparability. Gate 8 divides one sample's depth-normalised load by the
## highest of the others, which measures the SITE only if extraction and library prep were equal.
## Samples processed in different batches confound place with processing, and the PFI report
## carries no batch metadata for the engine to detect it. Set `independent = true` whenever the
## inputs are not one facility's batch: different donors, different studies, different runs.

workflow TriageBatch {
  input {
    Array[File] reports
    Boolean     independent   = false
    Boolean     html_report   = true
    Boolean     with_fastq    = false
    String      docker        = "htx-triage:1.0.0"
    String      batch_name    = "batch"
  }

  parameter_meta {
    reports:     "PFI single-page HTML reports, one per sample (<sample>_en.html)."
    independent: "True when the samples are NOT from one site/batch. Turns gate 8 off so a fold-change between them is never read as site enrichment."
    html_report: "Also emit the self-contained evidence report for the whole batch."
    with_fastq:  "Opt in to the gates that read outside the HTML report (gate 6). Requires the raw reads to be present, which they are not under WDL localisation, so this is off by default and exists for completeness."
  }

  call Triage {
    input:
      reports     = reports,
      independent = independent,
      html_report = html_report,
      with_fastq  = with_fastq,
      batch_name  = batch_name,
      docker      = docker
  }

  output {
    Array[File] tsvs        = Triage.tsvs
    File?       evidence    = Triage.evidence
    File        summary     = Triage.summary
    File        versions    = Triage.versions
  }

  meta {
    description: "Deterministic triage of PFI metagenomic reports. Emits tiers, never diagnoses."
    outputs: {
      tsvs:     "One TSV per sample: sample verdict, then a row per taxon and per AMR gene, each carrying the rule that produced it.",
      evidence: "Self-contained HTML evidence report for the batch (only when html_report=true).",
      summary:  "The engine's stdout — sample verdicts and the rows that drove them.",
      versions: "Engine version and rule-file fingerprint, so a run records WHICH rules produced its verdicts."
    }
  }
}

task Triage {
  input {
    Array[File] reports
    Boolean     independent
    Boolean     html_report
    Boolean     with_fastq
    String      batch_name
    String      docker
    Int         cpu       = 1
    Int         memory_gb = 4
    Int         disk_gb   = 20
  }

  command <<<
    set -euo pipefail
    mkdir -p out

    # Record which rules produced these verdicts. The engine is stable; the rule file is the
    # part that moves, so a run that cannot name its rules cannot be reproduced.
    triage --version > out/versions.txt

    # Localised paths are absolute and generated by the engine at run time; the engine takes
    # them directly rather than resolving a stem against a hard-coded root.
    triage \
      --outdir=out \
      ~{true="--independent" false="" independent} \
      ~{true="--with-fastq" false="" with_fastq} \
      ~{sep=" " reports} \
      | tee out/~{batch_name}_summary.txt

    if ~{true="true" false="false" html_report}; then
      triage \
        --html --out=out/~{batch_name}_evidence.html \
        ~{true="--independent" false="" independent} \
        ~{sep=" " reports}
    fi
  >>>

  output {
    Array[File] tsvs     = glob("out/triage_*.tsv")
    File?       evidence = "out/~{batch_name}_evidence.html"
    File        summary  = "out/~{batch_name}_summary.txt"
    File        versions = "out/versions.txt"
  }

  runtime {
    docker: docker
    cpu:    cpu
    memory: "~{memory_gb} GB"
    disks:  "local-disk ~{disk_gb} HDD"
    # Deterministic and side-effect free: same report in, same verdicts out, forever.
    # That is what makes call-caching safe here.
    maxRetries: 1
  }
}

task TriageOne {
  ## Single report. Gate 8 (cross-sample enrichment) cannot run and the output says so — every
  ## non-threat row is tagged "NOT shown to be site-specific". Do not use this to fan a batch out
  ## across parallel tasks: that silently discards the comparison that separates a site finding
  ## from ordinary background.
  input {
    File   report
    String docker    = "htx-triage:1.0.0"
    Int    cpu       = 1
    Int    memory_gb = 4
    Int    disk_gb   = 10
  }

  command <<<
    set -euo pipefail
    mkdir -p out
    triage --version > out/versions.txt
    triage --outdir=out ~{report} | tee out/summary.txt
    triage --html --out=out/evidence.html ~{report}
  >>>

  output {
    File tsv      = glob("out/triage_*.tsv")[0]
    File evidence = "out/evidence.html"
    File summary  = "out/summary.txt"
    File versions = "out/versions.txt"
  }

  runtime {
    docker: docker
    cpu:    cpu
    memory: "~{memory_gb} GB"
    disks:  "local-disk ~{disk_gb} HDD"
    maxRetries: 1
  }
}
