#!/usr/bin/env python3
"""Export triage_rules.json as a human reference: Markdown + Excel.

    python3 analysis/export_rules.py

Writes docs/reference_rules.md and analysis/triage_rules.xlsx. Both are generated
artefacts — edit triage_rules.json, never these. The PFIDB column is an exact-string
check against PFI_DB/PFIDB_v5_0.xlsx, because triage.py matches taxon names with
dict.get(): a name that differs by one character never fires.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULES = json.load(open(os.path.join(ROOT, 'analysis', 'triage_rules.json')))
PFIDB = os.path.join(ROOT, 'PFI_DB', 'PFIDB_v5_0.xlsx')


def pfidb_names():
    """Species names in PFIDB v5, or an empty set if the workbook is not present."""
    try:
        import openpyxl
    except ImportError:
        return set()
    if not os.path.exists(PFIDB):
        return set()
    ws = openpyxl.load_workbook(PFIDB, read_only=True).active
    return {str(r[0]).strip() for r in ws.iter_rows(values_only=True) if r[0]}


def entries(section):
    return {k: v for k, v in RULES[section].items() if k != '_comment' and isinstance(v, dict)}


def rows():
    """Every export table, as (sheet_name, header, list-of-rows). One definition, two writers."""
    db = pfidb_names()
    hit = (lambda n: ('yes' if n in db else 'NO - name mismatch')) if db else (lambda n: 'not checked')

    thr = [[n, v.get('taxid', ''), v['tier'], v['genome'],
            ', '.join(v['markers']) or '-',
            ', '.join(v.get('supporting_markers', [])) or '-',
            'two-way' if v['markers'] else ('one-way' if v.get('supporting_markers') else 'none'),
            v.get('subspecies_required', ''),
            ', '.join(v['near_neighbours']) or '-',
            hit(n)]
           for n, v in sorted(entries('threat_list').items(), key=lambda x: (x[1]['tier'], x[0]))]

    watch = [[n, v.get('taxid', ''), v['priority'], ', '.join(v['escalating_classes']),
              v['note'], hit(n)]
             for n, v in sorted(entries('clinical_watchlist').items())]

    users = {}
    for n, v in entries('threat_list').items():
        for m in v['markers']:
            users.setdefault(m, []).append(n + ' (two-way)')
        for m in v.get('supporting_markers', []):
            users.setdefault(m, []).append(n + ' (one-way)')
    mark = [[m, pat, ', '.join(users.get(m, [])) or '- unused -']
            for m, pat in sorted(RULES['marker_patterns'].items())]

    amr = [[g, v.get('class', ''), v.get('drug', ''), v.get('requires', ''), v.get('why', '')]
           for g, v in sorted(RULES['amr_classes'].items()) if isinstance(v, dict)]

    mech = [[k] + k.split('|') + [v] for k, v in sorted(RULES['mechanism_classes'].items())
            if isinstance(v, str) and '|' in k]

    hints = [[g, ', '.join(v.get('taxa', [])), v.get('basis', '')]
             for g, v in sorted(RULES['amr_host_hints'].items()) if isinstance(v, dict)]

    thresh = [[k, str(v)] for k, v in sorted(RULES['thresholds'].items())]
    for sect in ('class_thresholds', 'group_thresholds', 'long_read_thresholds'):
        for k, v in sorted(RULES[sect].items()):
            if isinstance(v, dict):
                thresh.append([f'{sect}.{k}', json.dumps({a: b for a, b in v.items()
                                                          if not a.startswith('_') and a != 'why'})])

    return [
        ('threat_list', ['Species', 'Taxid', 'CDC tier', 'Genome', 'Confirmatory markers (two-way)',
                         'Supporting markers (one-way)', 'Gate 10 mode', 'Subspecies required',
                         'Near neighbours', 'In PFIDB v5'], thr),
        ('clinical_watchlist', ['Species', 'Taxid', 'Priority', 'Escalating AMR classes',
                                'Note', 'In PFIDB v5'], watch),
        ('marker_patterns', ['Marker', 'Regex', 'Used by'], mark),
        ('amr_classes', ['MEGARes group', 'Class', 'Drug', 'Requires', 'Why'], amr),
        ('mechanism_classes', ['Key', 'Type', 'Mechanism', 'Class'], mech),
        ('amr_host_hints', ['MEGARes group', 'Expected host genera', 'Basis'], hints),
        ('kitome_genera', ['Genus'], [[x] for x in sorted(RULES['kitome_genera'])]),
        ('taxonomy_notes', ['Species', 'Note'], sorted(RULES['taxonomy_notes'].items())),
        ('thresholds', ['Setting', 'Value'], thresh),
    ]


def write_markdown(tables, path):
    esc = lambda c: str(c).replace('|', r'\|').replace('\n', ' ')
    out = ['# Rule-file reference — species, markers and thresholds', '',
           'Generated by `analysis/export_rules.py` from `analysis/triage_rules.json`.',
           '**Do not edit this file** — edit the JSON and re-run the exporter.', '',
           'The *In PFIDB v5* column is an exact-string check against `PFI_DB/PFIDB_v5_0.xlsx`.',
           'Since the taxid keying change this is advisory, not fatal: `triage.py` matches on',
           '`Taxid` first and falls back to the name. A `NO - name mismatch` row still fires,',
           'but only for reports that carry a taxid column.', '']
    for name, header, data in tables:
        out += [f'## {name} — {len(data)} entries', '',
                '| ' + ' | '.join(header) + ' |',
                '|' + '|'.join('---' for _ in header) + '|']
        out += ['| ' + ' | '.join(esc(c) for c in r) + ' |' for r in data]
        out += ['']
    open(path, 'w').write('\n'.join(out))


def write_excel(tables, path):
    try:
        import openpyxl
        from openpyxl.styles import Font, Alignment
    except ImportError:
        return None
    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    for name, header, data in tables:
        ws = wb.create_sheet(name[:31])
        ws.append(header)
        for c in ws[1]:
            c.font = Font(bold=True)
            c.alignment = Alignment(vertical='top', wrap_text=True)
        for r in data:
            ws.append([str(c) for c in r])
        for i, h in enumerate(header, 1):
            width = max([len(h)] + [len(str(r[i - 1])) for r in data if i <= len(r)])
            ws.column_dimensions[openpyxl.utils.get_column_letter(i)].width = min(60, width + 2)
        ws.freeze_panes = 'A2'
        ws.auto_filter.ref = ws.dimensions
    wb.save(path)
    return path


if __name__ == '__main__':
    tables = rows()
    md = os.path.join(ROOT, 'docs', 'reference_rules.md')
    xl = os.path.join(ROOT, 'analysis', 'triage_rules.xlsx')
    write_markdown(tables, md)
    got = write_excel(tables, xl)
    for name, _h, data in tables:
        print(f'  {name:20} {len(data):4} rows')
    print(f'\n{os.path.relpath(md, ROOT)}  ({os.path.getsize(md)/1024:.0f} KB)')
    print(f'{os.path.relpath(xl, ROOT)}' if got else 'openpyxl not installed - Excel skipped')
